name: innova_craft_studio
description: "Innova Craft Studio - El Yapımı Ürünler ve Sanat Eserleri"
publish_to: 'none'

version: 1.3.9+32

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Network
  dio: ^5.4.0
  
  # Auth
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.10
  
  video_player: ^2.8.2

  # Notifications
  flutter_local_notifications: ^17.2.3
  flutter_app_badger: ^1.5.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # WebView (for Iyzico payment)
  webview_flutter: ^4.4.2
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Utils
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # Image Viewer
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # Network Logging
  pretty_dio_logger: ^1.3.1
  
  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ics_logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/ics_logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ics_logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/ics_logo.jpg"
